# Generated by Django 5.2.5 on 2025-08-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('nome_guerra', models.CharField(max_length=100, verbose_name='Nome de Guerra')),
                ('saram', models.IntegerField(unique=True, verbose_name='SARAM')),
                ('telefone', models.BigIntegerField(blank=True, null=True, verbose_name='Telefone')),
                ('turma', models.CharField(blank=True, max_length=100, verbose_name='Turma')),
                ('posto', models.CharField(blank=True, max_length=50, verbose_name='Posto')),
                ('graduacao', models.CharField(blank=True, max_length=50, verbose_name='Graduação')),
                ('secao_om', models.CharField(max_length=100, verbose_name='Seção/OM')),
                ('oficial', models.BooleanField(default=False, verbose_name='É Oficial?')),
            ],
            options={
                'verbose_name': 'Militar',
                'verbose_name_plural': 'Militares',
            },
        ),
        migrations.CreateModel(
            name='PATD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transgressao', models.TextField(verbose_name='Transgressão')),
                ('numero_patd', models.IntegerField(unique=True, verbose_name='N° PATD')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_termino', models.DateTimeField(blank=True, null=True, verbose_name='Data de Término')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patds', to='Ouvidoria.militar', verbose_name='Militar Acusado')),
                ('oficial_responsavel', models.ForeignKey(blank=True, limit_choices_to={'oficial': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patds_responsaveis', to='Ouvidoria.militar', verbose_name='Oficial Responsável')),
            ],
            options={
                'verbose_name': 'PATD',
                'verbose_name_plural': 'PATDs',
            },
        ),
    ]
