# Generated by Django 5.2.5 on 2025-08-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militar',
            name='graduacao',
        ),
        migrations.RemoveField(
            model_name='militar',
            name='secao_om',
        ),
        migrations.RemoveField(
            model_name='militar',
            name='telefone',
        ),
        migrations.AddField(
            model_name='militar',
            name='especializacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especialização'),
        ),
        migrations.AddField(
            model_name='militar',
            name='om',
            field=models.CharField(blank=True, max_length=100, verbose_name='OM'),
        ),
        migrations.AddField(
            model_name='militar',
            name='quad',
            field=models.CharField(blank=True, max_length=50, verbose_name='QUAD'),
        ),
        migrations.AddField(
            model_name='militar',
            name='setor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='militar',
            name='situacao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='militar',
            name='subsetor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subsetor'),
        ),
    ]
