# Generated by Django 5.2.5 on 2025-08-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0002_remove_militar_graduacao_remove_militar_secao_om_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='saram',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='SARAM'),
        ),
    ]
