# Generated by Django 5.2.5 on 2025-08-15 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0003_alter_militar_saram'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='data_ocorrencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
    ]
