# Generated by Django 5.2.5 on 2025-08-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0004_patd_data_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='status',
            field=models.CharField(choices=[('definicao_oficial', 'Aguardando definição do Oficial'), ('ciencia_militar', 'Aguardando ciência do militar'), ('aguardando_justificativa', 'Aguardando Justificativa (5 dias)'), ('prazo_expirado', 'Prazo expirado'), ('em_apuracao', 'Aguardando Apuração'), ('aguardando_punicao', 'Aguardando Aplicação da Punição'), ('aguardando_assinatura', 'Aguardando Assinatura NPD')], default='definicao_oficial', max_length=50, verbose_name='Status'),
        ),
    ]
