# Generated by Django 5.2.5 on 2025-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0005_patd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='assinatura_oficial',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura do Oficial (Base64)'),
        ),
    ]
