# Generated by Django 5.2.5 on 2025-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0006_patd_assinatura_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='assinatura',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura Padrão (Base64)'),
        ),
    ]
