# Generated by Django 5.2.5 on 2025-08-15 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0007_militar_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='testemunha1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patds_testemunha1', to='Ouvidoria.militar', verbose_name='1ª Testemunha'),
        ),
        migrations.AddField(
            model_name='patd',
            name='testemunha2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patds_testemunha2', to='Ouvidoria.militar', verbose_name='2ª Testemunha'),
        ),
    ]
