# Generated by Django 5.2.5 on 2025-08-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0008_patd_testemunha1_patd_testemunha2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comandante_gsd', models.ForeignKey(blank=True, limit_choices_to={'oficial': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Ouvidoria.militar', verbose_name='Comandante do GSD Padrão')),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
    ]
