# Generated by Django 5.2.5 on 2025-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0009_configuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='documento_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto do Documento'),
        ),
    ]
