# Generated by Django 5.2.5 on 2025-08-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0010_patd_documento_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='assinatura_militar_ciencia',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura de Ciência do Militar (Base64)'),
        ),
    ]
