# Generated by Django 5.2.5 on 2025-08-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0011_patd_assinatura_militar_ciencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='alegacao_defesa',
            field=models.TextField(blank=True, null=True, verbose_name='Alegação de Defesa'),
        ),
        migrations.AddField(
            model_name='patd',
            name='data_ciencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Ciência'),
        ),
    ]
