# Generated by Django 5.2.5 on 2025-08-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0012_patd_alegacao_defesa_patd_data_ciencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='prazo_defesa_dias',
            field=models.IntegerField(default=5, verbose_name='Prazo para Defesa (dias úteis)'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='status',
            field=models.CharField(choices=[('definicao_oficial', 'Aguardando definição do Oficial'), ('ciencia_militar', 'Aguardando ciência do militar'), ('aguardando_justificativa', 'Aguardando Justificativa'), ('prazo_expirado', 'Prazo expirado'), ('em_apuracao', 'Aguardando Apuração'), ('aguardando_punicao', 'Aguardando Aplicação da Punição'), ('aguardando_assinatura', 'Aguardando Assinatura NPD')], default='definicao_oficial', max_length=50, verbose_name='Status'),
        ),
    ]
