# Generated by Django 5.2.5 on 2025-08-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0013_configuracao_prazo_defesa_dias_alter_patd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='prazo_defesa_minutos',
            field=models.IntegerField(default=0, verbose_name='Prazo para Defesa (minutos)'),
        ),
    ]
