# Generated by Django 5.2.5 on 2025-08-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0014_configuracao_prazo_defesa_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='assinatura_testemunha1',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura da 1ª Testemunha (Base64)'),
        ),
        migrations.AddField(
            model_name='patd',
            name='assinatura_testemunha2',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura da 2ª Testemunha (Base64)'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='status',
            field=models.CharField(choices=[('definicao_oficial', 'Aguardando definição do Oficial'), ('ciencia_militar', 'Aguardando ciência do militar'), ('aguardando_justificativa', 'Aguardando Justificativa'), ('prazo_expirado', 'Prazo expirado'), ('preclusao', 'Preclusão - Sem Defesa'), ('em_apuracao', 'Aguardando Apuração'), ('aguardando_punicao', 'Aguardando Aplicação da Punição'), ('aguardando_assinatura', 'Aguardando Assinatura NPD')], default='definicao_oficial', max_length=50, verbose_name='Status'),
        ),
    ]
