# Generated by Django 5.2.5 on 2025-08-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0015_patd_assinatura_testemunha1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='militar',
            options={},
        ),
        migrations.AlterModelTable(
            name='militar',
            table='Efetivo_Militar',
        ),
    ]
