# Generated by Django 5.2.5 on 2025-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0016_alter_militar_options_alter_militar_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='circunstancias',
            field=models.JSONField(blank=True, null=True, verbose_name='Atenuantes e Agravantes'),
        ),
        migrations.AddField(
            model_name='patd',
            name='itens_enquadrados',
            field=models.JSONField(blank=True, null=True, verbose_name='Itens Enquadrados na Análise'),
        ),
        migrations.AddField(
            model_name='patd',
            name='punicao_sugerida',
            field=models.TextField(blank=True, null=True, verbose_name='Punição Sugerida pela IA'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='status',
            field=models.CharField(choices=[('definicao_oficial', 'Aguardando definição do Oficial'), ('ciencia_militar', 'Aguardando ciência do militar'), ('aguardando_justificativa', 'Aguardando Justificativa'), ('prazo_expirado', 'Prazo expirado'), ('preclusao', 'Preclusão - Sem Defesa'), ('em_apuracao', 'Em Apuração'), ('apuracao_preclusao', 'Em Apuração (Preclusão)'), ('aguardando_punicao', 'Aguardando Aplicação da Punição'), ('aguardando_assinatura', 'Aguardando Assinatura NPD')], default='definicao_oficial', max_length=50, verbose_name='Status'),
        ),
    ]
