# Generated by Django 5.2.5 on 2025-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0017_patd_circunstancias_patd_itens_enquadrados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='oficio_transgrecao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ofício Transgressão'),
        ),
        migrations.AddField(
            model_name='patd',
            name='protocolo_comaer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Protocolo COMAER'),
        ),
    ]
