# Generated by Django 5.2.5 on 2025-09-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0018_patd_oficio_transgrecao_patd_protocolo_comaer'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='data_oficio',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Ofício'),
        ),
    ]
