# Generated by Django 5.2.5 on 2025-09-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0019_patd_data_oficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='alegacao_defesa_resumo',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo da Alegação de Defesa'),
        ),
        migrations.AddField(
            model_name='patd',
            name='comportamento',
            field=models.CharField(blank=True, default='Permanece no "Bom comportamento"', max_length=100, null=True, verbose_name='Comportamento'),
        ),
        migrations.AddField(
            model_name='patd',
            name='comprovante',
            field=models.TextField(blank=True, null=True, verbose_name='Comprovante da Transgressão'),
        ),
        migrations.AddField(
            model_name='patd',
            name='data_alegacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Alegação de Defesa'),
        ),
        migrations.AddField(
            model_name='patd',
            name='dias_punicao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dias de Punição'),
        ),
        migrations.AddField(
            model_name='patd',
            name='natureza_transgressao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Natureza da Transgressão'),
        ),
        migrations.AddField(
            model_name='patd',
            name='punicao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Punição'),
        ),
        migrations.AddField(
            model_name='patd',
            name='transgressao_afirmativa',
            field=models.TextField(blank=True, null=True, verbose_name='Transgressão Afirmativa'),
        ),
    ]
