# Generated by Django 5.2.5 on 2025-09-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0020_patd_alegacao_defesa_resumo_patd_comportamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='ocorrencia_reescrita',
            field=models.TextField(blank=True, null=True, verbose_name='Ocorrência Reescrita (Formal)'),
        ),
    ]
