# Generated by Django 5.2.5 on 2025-09-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0021_patd_ocorrencia_reescrita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patd',
            name='ocorrencia_reescrita',
            field=models.TextField(blank=True, null=True, verbose_name='Ocorrência Reescrita'),
        ),
    ]
