# Generated by Django 5.2.5 on 2025-09-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0023_alter_patd_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patd',
            name='assinatura_militar_ciencia',
        ),
        migrations.AddField(
            model_name='patd',
            name='assinaturas_militar',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Assinaturas do Militar Arrolado (Base64)'),
        ),
    ]
