# Generated by Django 5.2.5 on 2025-09-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0025_alter_patd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='senha_unica',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha Única'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='status',
            field=models.CharField(choices=[('definicao_oficial', 'Aguardando definição do Oficial'), ('aguardando_aprovacao_atribuicao', 'Aguardando aprovação de atribuição de oficial'), ('ciencia_militar', 'Aguardando ciência do militar'), ('aguardando_justificativa', 'Aguardando Justificativa'), ('prazo_expirado', 'Prazo expirado'), ('preclusao', 'Preclusão - Sem Defesa'), ('em_apuracao', 'Em Apuração'), ('apuracao_preclusao', 'Em Apuração (Preclusão)'), ('aguardando_punicao', 'Aguardando Aplicação da Punição'), ('analise_comandante', 'Em Análise pelo Comandante'), ('aguardando_assinatura_npd', 'Aguardando Assinatura NPD'), ('finalizado', 'Finalizado'), ('aguardando_punicao_alterar', 'Aguardando Punição (alterar)')], default='definicao_oficial', max_length=50, verbose_name='Status'),
        ),
    ]
