# Generated by Django 5.2.5 on 2025-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0027_patd_data_publicacao_punicao_alter_patd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='texto_reconsideracao',
            field=models.TextField(blank=True, null=True, verbose_name='Texto da Reconsideração'),
        ),
    ]
