# Generated by Django 5.2.5 on 2025-09-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0028_patd_texto_reconsideracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='data_reconsideracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Reconsideração'),
        ),
    ]
