# Generated by Django 5.2.5 on 2025-09-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0029_patd_data_reconsideracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patd',
            name='oficio_transgrecao',
        ),
        migrations.AddField(
            model_name='patd',
            name='oficio_transgressao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ofício da Transgressão'),
        ),
    ]
