# Generated by Django 5.2.5 on 2025-09-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0030_remove_patd_oficio_transgrecao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='texto_relatorio',
            field=models.TextField(blank=True, null=True, verbose_name='Texto do Relatório de Apuração'),
        ),
    ]
