# Generated by Django 5.2.5 on 2025-09-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0031_patd_texto_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='assinatura_alegacao_defesa',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura da Alegação de Defesa (Base64)'),
        ),
        migrations.AddField(
            model_name='patd',
            name='assinatura_reconsideracao',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura da Reconsideração (Base64)'),
        ),
    ]
