# Generated by Django 5.2.5 on 2025-09-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0032_patd_assinatura_alegacao_defesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='comentario_comandante',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário do Comandante para Alteração'),
        ),
    ]
