# Generated by Django 5.2.5 on 2025-09-17 13:41

import Ouvidoria.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0033_patd_comentario_comandante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patd',
            name='comentario_comandante',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário do Comandante para Retorno'),
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=Ouvidoria.models.patd_anexo_path, verbose_name='Ficheiro')),
                ('tipo', models.CharField(choices=[('defesa', 'Alegação de Defesa'), ('reconsideracao', 'Pedido de Reconsideração')], max_length=20)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('patd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='Ouvidoria.patd')),
            ],
        ),
    ]
