# Generated by Django 5.2.5 on 2025-09-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0034_alter_patd_comentario_comandante_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='status_anterior',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Anterior'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='tipo',
            field=models.CharField(choices=[('defesa', 'Defesa'), ('reconsideracao', 'Reconsideração')], max_length=20),
        ),
    ]
