# Generated by Django 5.2.5 on 2025-09-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0036_patd_boletim_publicacao_alter_patd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='justificado',
            field=models.BooleanField(default=False, verbose_name='Transgressão Justificada'),
        ),
    ]
