# Generated by Django 4.2.24 on 2025-09-19 00:18

import Ouvidoria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0037_patd_justificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='anexo_reconsideracao_oficial',
            field=models.FileField(blank=True, null=True, upload_to=Ouvidoria.models.patd_anexo_path, verbose_name='Anexo da Reconsideração do Oficial'),
        ),
        migrations.AddField(
            model_name='patd',
            name='assinaturas_npd_reconsideracao',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Assinaturas da NPD de Reconsideração (Base64)'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='tipo',
            field=models.CharField(choices=[('defesa', 'Defesa'), ('reconsideracao', 'Reconsideração'), ('reconsideracao_oficial', 'Reconsideração Oficial')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patd',
            name='status',
            field=models.CharField(choices=[('definicao_oficial', 'Aguardando definição do Oficial'), ('aguardando_aprovacao_atribuicao', 'Aguardando aprovação de atribuição de oficial'), ('ciencia_militar', 'Aguardando ciência do militar'), ('aguardando_justificativa', 'Aguardando Justificativa'), ('prazo_expirado', 'Prazo expirado'), ('preclusao', 'Preclusão - Sem Defesa'), ('em_apuracao', 'Em Apuração'), ('apuracao_preclusao', 'Em Apuração (Preclusão)'), ('aguardando_punicao', 'Aguardando Aplicação da Punição'), ('aguardando_punicao_alterar', 'Aguardando Punição (alterar)'), ('analise_comandante', 'Em Análise pelo Comandante'), ('aguardando_assinatura_npd', 'Aguardando Assinatura NPD'), ('periodo_reconsideracao', 'Período de Reconsideração'), ('em_reconsideracao', 'Em Reconsideração'), ('aguardando_comandante_base', 'Aguardando Comandante da Base'), ('aguardando_publicacao', 'Aguardando publicação'), ('finalizado', 'Finalizado')], default='definicao_oficial', max_length=50, verbose_name='Status'),
        ),
    ]
