# Generated by Django 4.2.24 on 2025-10-01 14:55

import Ouvidoria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0040_alter_patd_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patd',
            name='assinatura_alegacao_defesa',
            field=models.FileField(blank=True, null=True, upload_to=Ouvidoria.models.patd_signature_path, verbose_name='Assinatura da Alegação de Defesa'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='assinatura_oficial',
            field=models.FileField(blank=True, null=True, upload_to=Ouvidoria.models.patd_signature_path, verbose_name='Assinatura do Oficial'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='assinatura_reconsideracao',
            field=models.FileField(blank=True, null=True, upload_to=Ouvidoria.models.patd_signature_path, verbose_name='Assinatura da Reconsideração'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='assinatura_testemunha1',
            field=models.FileField(blank=True, null=True, upload_to=Ouvidoria.models.patd_signature_path, verbose_name='Assinatura da 1ª Testemunha'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='assinatura_testemunha2',
            field=models.FileField(blank=True, null=True, upload_to=Ouvidoria.models.patd_signature_path, verbose_name='Assinatura da 2ª Testemunha'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='assinaturas_militar',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Assinaturas do Militar Arrolado (Caminhos)'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='status',
            field=models.CharField(choices=[('definicao_oficial', 'Aguardando definição do Oficial'), ('aguardando_aprovacao_atribuicao', 'Aguardando aprovação de atribuição de oficial'), ('ciencia_militar', 'Aguardando ciência do militar'), ('aguardando_justificativa', 'Aguardando Justificativa'), ('prazo_expirado', 'Prazo expirado'), ('preclusao', 'Preclusão - Sem Defesa'), ('em_apuracao', 'Em Apuração'), ('apuracao_preclusao', 'Em Apuração (Preclusão)'), ('aguardando_punicao', 'Aguardando Aplicação da Punição'), ('aguardando_punicao_alterar', 'Aguardando Punição (alterar)'), ('analise_comandante', 'Em Análise pelo Comandante'), ('aguardando_assinatura_npd', 'Aguardando Assinatura NPD'), ('periodo_reconsideracao', 'Período de Reconsideração'), ('em_reconsideracao', 'Em Reconsideração'), ('aguardando_comandante_base', 'Aguardando Comandante da Base'), ('aguardando_preenchimento_npd_reconsideracao', 'Aguardando preenchimento NPD Reconsideração'), ('aguardando_publicacao', 'Aguardando publicação'), ('finalizado', 'Finalizado')], default='definicao_oficial', max_length=50, verbose_name='Status'),
        ),
    ]
