# Generated by Django 4.2.24 on 2025-10-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0041_alter_patd_assinatura_alegacao_defesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='tipo',
            field=models.CharField(choices=[('defesa', 'Defesa'), ('reconsideracao', 'Reconsideração'), ('reconsideracao_oficial', 'Reconsideração Oficial'), ('assinatura_ciencia', 'Assinatura de Ciência')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patd',
            name='comportamento',
            field=models.CharField(blank=True, default='Permanece no "Bom comportamento"', max_length=100, verbose_name='Comportamento'),
        ),
    ]
