# Generated by Django 4.2.24 on 2025-10-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0042_alter_anexo_tipo_alter_patd_comportamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='comandante_bagl',
            field=models.ForeignKey(blank=True, limit_choices_to={'oficial': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Ouvidoria.militar', verbose_name='Comandante da Base (BAGL)'),
        ),
        migrations.AddField(
            model_name='patd',
            name='nova_punicao_dias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nova Punição (Dias)'),
        ),
        migrations.AddField(
            model_name='patd',
            name='nova_punicao_tipo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nova Punição (Tipo)'),
        ),
    ]
