# Generated by Django 4.2.24 on 2025-10-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0043_configuracao_comandante_bagl_patd_nova_punicao_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='relatorio_final',
            field=models.TextField(blank=True, null=True, verbose_name='Relatório Final'),
        ),
    ]
