# Generated by Django 4.2.24 on 2025-12-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0001_initial'),
        ('login', '0002_alter_userprofile_militar'),
        ('Ouvidoria', '0045_alter_patd_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='comandante_bagl',
            field=models.ForeignKey(blank=True, limit_choices_to={'oficial': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Secao_pessoal.efetivo', verbose_name='Comandante da Base (BAGL)'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='comandante_gsd',
            field=models.ForeignKey(blank=True, limit_choices_to={'oficial': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Secao_pessoal.efetivo', verbose_name='Comandante do GSD Padrão'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='militar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patds', to='Secao_pessoal.efetivo', verbose_name='Militar Acusado'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='oficial_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'oficial': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patds_responsaveis', to='Secao_pessoal.efetivo', verbose_name='Oficial Responsável'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='testemunha1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patds_testemunha1', to='Secao_pessoal.efetivo', verbose_name='1ª Testemunha'),
        ),
        migrations.AlterField(
            model_name='patd',
            name='testemunha2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patds_testemunha2', to='Secao_pessoal.efetivo', verbose_name='2ª Testemunha'),
        ),
        migrations.DeleteModel(
            name='Militar',
        ),
    ]
