# Generated by Django 4.2.24 on 2026-01-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0047_create_ouvidoria_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='oficio_lancamento_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto do Ofício de Lançamento'),
        ),
    ]
