# Generated by Django 4.2.24 on 2026-01-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0048_patd_oficio_lancamento_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patd',
            name='oficio_lancamento_texto',
        ),
        migrations.AlterField(
            model_name='anexo',
            name='tipo',
            field=models.CharField(choices=[('defesa', 'Defesa'), ('reconsideracao', 'Reconsideração'), ('reconsideracao_oficial', 'Reconsideração Oficial'), ('assinatura_ciencia', 'Assinatura de Ciência'), ('oficio_lancamento', 'Ofício de Lançamento')], max_length=30),
        ),
    ]
