# Generated by Django 4.2.24 on 2026-02-04 11:43

import Ouvidoria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0049_remove_patd_oficio_lancamento_texto_alter_anexo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patd',
            name='assinatura_oficial',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=Ouvidoria.models.patd_signature_path, verbose_name='Assinatura do Oficial'),
        ),
    ]
