# Generated by Django 4.2.24 on 2026-02-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0050_alter_patd_assinatura_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
