# Generated by Django 4.2.24 on 2026-02-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0051_patd_arquivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='motivo_arquivamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Arquivamento'),
        ),
    ]
