# Generated by Django 4.2.24 on 2026-02-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0006_notificacao'),
        ('Ouvidoria', '0052_patd_motivo_arquivamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='patd',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AddField(
            model_name='patd',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Restauração'),
        ),
        migrations.AddField(
            model_name='patd',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_patds', to='Secao_pessoal.efetivo', verbose_name='Restaurado por'),
        ),
    ]
