# Generated by Django 4.2.24 on 2026-02-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0053_patd_deleted_patd_deleted_at_patd_restored_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patd',
            name='numero_patd',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='N° PATD'),
        ),
    ]
