# Generated by Django 4.2.24 on 2026-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0054_alter_patd_numero_patd'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='numero_patd_anterior',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° PATD Original (Lixeira)'),
        ),
    ]
