# Generated by Django 4.2.24 on 2026-03-03 13:15

import Ouvidoria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0055_patd_numero_patd_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(upload_to=Ouvidoria.models.patd_anexo_path, validators=[Ouvidoria.models.validate_file_size], verbose_name='Ficheiro'),
        ),
    ]
