# Generated by Django 4.2.24 on 2026-03-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0056_alter_anexo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='justificativa_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto da Justificativa'),
        ),
    ]
