# Generated by Django 4.2.24 on 2026-03-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0057_patd_justificativa_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='tipo',
            field=models.CharField(choices=[('defesa', 'Defesa'), ('reconsideracao', 'Reconsideração'), ('reconsideracao_oficial', 'Reconsideração Oficial'), ('assinatura_ciencia', 'Assinatura de Ciência'), ('oficio_lancamento', 'Ofício de Lançamento'), ('documento_final', 'Documento Final Completo')], max_length=30),
        ),
    ]
