# Generated by Django 4.2.24 on 2026-04-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0058_alter_anexo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='prazo_override',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo de Defesa (override)'),
        ),
    ]
