# Generated by Django 4.2.24 on 2026-04-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0061_auto_accept_existing_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='dias_retencao_lixeira',
            field=models.IntegerField(default=30, verbose_name='Dias de retenção na lixeira'),
        ),
    ]
