# Generated by Django 4.2.24 on 2026-04-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0062_configuracao_dias_retencao_lixeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='tipo',
            field=models.CharField(choices=[('defesa', 'Defesa'), ('reconsideracao', 'Reconsideração'), ('reconsideracao_oficial', 'Reconsideração Oficial'), ('assinatura_ciencia', 'Assinatura de Ciência'), ('oficio_lancamento', 'Ofício de Lançamento'), ('ficha_individual', 'Ficha Individual'), ('formulario_resumo', 'Formulário de Resumo'), ('documento_final', 'Documento Final Completo')], max_length=30),
        ),
    ]
