# Generated by Django 4.2.24 on 2026-05-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0067_patd_assinatura_cmd_gsd_despacho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='comandante_bagl',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='comandante_gsd',
        ),
    ]
