# Generated by Django 4.2.24 on 2026-05-15 17:56

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0068_remove_configuracao_comandante_bagl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patd',
            name='numero_patd',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° PATD'),
        ),
        migrations.AddConstraint(
            model_name='patd',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.ExtractYear('data_inicio'), models.F('numero_patd'), condition=models.Q(('numero_patd__isnull', False)), name='unique_patd_numero_por_ano'),
        ),
    ]
