# Generated by Django 4.2.24 on 2026-05-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0071_fix_definicao_oficial_pos_defesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='datas_documentos',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Datas por Documento'),
        ),
    ]
