# Generated by Django 4.2.24 on 2026-06-06 16:17
# Rewritten to use CREATE INDEX CONCURRENTLY to avoid table locks in production.

from django.db import migrations, models


class Migration(migrations.Migration):
    # CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('Ouvidoria', '0073_add_confeccao_fr_ficha_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='patd',
                    name='arquivado',
                    field=models.BooleanField(db_index=True, default=False, verbose_name='Arquivado'),
                ),
                migrations.AlterField(
                    model_name='patd',
                    name='deleted',
                    field=models.BooleanField(db_index=True, default=False, verbose_name='Excluído'),
                ),
                migrations.AlterField(
                    model_name='patd',
                    name='status',
                    field=models.CharField(choices=[('definicao_oficial', 'Aguardando definição do Oficial'), ('aguardando_aprovacao_atribuicao', 'Aguardando aprovação de atribuição de oficial'), ('confeccao_fr_ficha', 'Confecção / FR e Ficha Individual'), ('ciencia_militar', 'Aguardando ciência do militar'), ('aguardando_justificativa', 'Aguardando Justificativa'), ('prazo_expirado', 'Prazo expirado'), ('preclusao', 'Preclusão - Sem Defesa'), ('em_apuracao', 'Em Apuração'), ('apuracao_preclusao', 'Em Apuração (Preclusão)'), ('aguardando_punicao', 'Aguardando Aplicação da Punição'), ('aguardando_punicao_alterar', 'Aguardando Punição (alterar)'), ('assinatura_cmd_gsd_despacho_abertura', 'Assinatura CMD GSD – Despacho de Abertura'), ('aplicacao_punicao_cmd_base', 'Aplicação da Punição – CMD da Base'), ('analise_comandante', 'Em Análise pelo Comandante'), ('aguardando_assinatura_npd', 'Aguardando Assinatura NPD'), ('periodo_reconsideracao', 'Período de Reconsideração'), ('em_reconsideracao', 'Em Reconsideração'), ('aguardando_comandante_base', 'Aguardando Comandante da Base'), ('aguardando_nova_punicao', 'Aguardando nova punição'), ('aguardando_publicacao', 'Aguardando publicação'), ('finalizado', 'Finalizado')], db_index=True, default='confeccao_fr_ficha', max_length=50, verbose_name='Status'),
                ),
                migrations.AddIndex(
                    model_name='patd',
                    index=models.Index(fields=['deleted', 'status'], name='patd_deleted_status_idx'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "Ouvidoria_patd_arquivado_80dc0143" ON "Ouvidoria_patd" ("arquivado")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "Ouvidoria_patd_arquivado_80dc0143"',
                ),
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "Ouvidoria_patd_deleted_81fc82e4" ON "Ouvidoria_patd" ("deleted")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "Ouvidoria_patd_deleted_81fc82e4"',
                ),
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "Ouvidoria_patd_status_ef2077da" ON "Ouvidoria_patd" ("status")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "Ouvidoria_patd_status_ef2077da"',
                ),
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "Ouvidoria_patd_status_ef2077da_like" ON "Ouvidoria_patd" ("status" varchar_pattern_ops)',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "Ouvidoria_patd_status_ef2077da_like"',
                ),
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "patd_deleted_status_idx" ON "Ouvidoria_patd" ("deleted", "status")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "patd_deleted_status_idx"',
                ),
            ],
        ),
    ]
