# Generated by Django 4.2.24 on 2026-06-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0074_alter_patd_arquivado_alter_patd_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='tipo',
            field=models.CharField(choices=[('defesa', 'Defesa'), ('reconsideracao', 'Reconsideração'), ('reconsideracao_oficial', 'Reconsideração Oficial'), ('assinatura_ciencia', 'Assinatura de Ciência'), ('oficio_lancamento', 'Ofício de Lançamento'), ('ficha_individual', 'Ficha Individual'), ('formulario_resumo', 'Formulário de Resumo'), ('documento_final', 'Documento Final Completo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patd',
            name='status',
            field=models.CharField(choices=[('definicao_oficial', 'Aguardando definição do Oficial'), ('aguardando_aprovacao_atribuicao', 'Aguardando aprovação de atribuição de oficial'), ('confeccao_fr_ficha', 'Confecção / FR e Ficha Individual'), ('ciencia_militar', 'Aguardando ciência do militar'), ('aguardando_justificativa', 'Aguardando Justificativa'), ('prazo_expirado', 'Prazo expirado'), ('preclusao', 'Preclusão - Sem Defesa'), ('em_apuracao', 'Em Apuração'), ('apuracao_preclusao', 'Em Apuração (Preclusão)'), ('aguardando_punicao', 'Aguardando Aplicação da Punição'), ('aguardando_punicao_alterar', 'Aguardando Punição (alterar)'), ('analise_comandante', 'Em Análise pelo Comandante'), ('aguardando_assinatura_npd', 'Aguardando Assinatura NPD'), ('periodo_reconsideracao', 'Período de Reconsideração'), ('em_reconsideracao', 'Em Reconsideração'), ('aguardando_nova_punicao', 'Aguardando nova punição'), ('aguardando_publicacao', 'Aguardando publicação'), ('finalizado', 'Finalizado')], db_index=True, default='confeccao_fr_ficha', max_length=50, verbose_name='Status'),
        ),
    ]
