# Generated by Django 4.2.24 on 2026-06-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0075_remove_cmd_base_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='fonte_padrao_documentos',
            field=models.CharField(blank=True, default='Times New Roman', max_length=60, verbose_name='Fonte padrão dos documentos'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='tamanho_fonte_documentos',
            field=models.PositiveIntegerField(default=12, verbose_name='Tamanho de fonte padrão (pt)'),
        ),
        migrations.AddField(
            model_name='patd',
            name='documento_html',
            field=models.JSONField(blank=True, default=list, verbose_name='HTML editado do documento'),
        ),
    ]
