# Generated by Django 4.2.24 on 2026-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0079_patd_organizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='patd',
            name='numero_patd_legado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° PATD (Sistema Antigo)'),
        ),
        migrations.AddField(
            model_name='patd',
            name='sistema_antigo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Importado do Sistema Antigo'),
        ),
    ]
