"""
Django settings for GsdAutomatico project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import mimetypes

# Força o sistema a reconhecer o CSS e o JS corretamente (Corrige o site "feio" no Windows)
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("text/javascript", ".js", True)

load_dotenv(override=True)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'daphne',                          # ASGI server com suporte a WebSockets
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',                        # Django Channels — real-time
    'Ouvidoria',
    'login',
    'informatica',
    'Secao_pessoal',
    'Secao_operacoes',
    'caixa_entrada',
    'home',
    'chamados',
    'notificacoes',
    'chamada.apps.ChamadaConfig',
    'ESI.apps.EsiConfig',
    'SCIM.apps.ScimConfig',
]

# ── Django Channels ───────────────────────────────────────────────────────────
ASGI_APPLICATION = 'GsdAutomatico.asgi.application'

# Variáveis definidas como string vazia são tratadas como ausentes (usa `or`)
_REDIS_URL  = os.getenv('REDIS_URL')         or None
_BROKER_URL = os.getenv('CELERY_BROKER_URL') or None
_HAS_REDIS  = bool(_REDIS_URL or _BROKER_URL)

if _HAS_REDIS:
    # Ambiente com Redis (produção / Docker)
    _REDIS_URL  = _REDIS_URL  or 'redis://127.0.0.1:6379/1'
    _BROKER_URL = _BROKER_URL or 'redis://127.0.0.1:6379/0'
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [_REDIS_URL],
                "capacity": 1500,
                "expiry": 10,
            },
        }
    }
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': _REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'RETRY_ON_TIMEOUT': True,
                'MAX_CONNECTIONS': 20,
                'CONNECTION_POOL_KWARGS': {'max_connections': 20},
            },
            'TIMEOUT': 300,
        }
    }
else:
    # Sem Redis — usa backends em memória (desenvolvimento local)
    _BROKER_URL = 'memory://'
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# ── Celery ────────────────────────────────────────────────────────────────────
CELERY_BROKER_URL = _BROKER_URL
CELERY_RESULT_BACKEND = _REDIS_URL or 'cache+memory://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Sao_Paulo'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300        # 5 min — mata workers travados
CELERY_TASK_SOFT_TIME_LIMIT = 270   # aviso 30s antes
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = None  # tenta reconectar indefinidamente
CELERY_BROKER_POOL_LIMIT = 10               # limite de conexões simultâneas ao broker
CELERY_WORKER_PREFETCH_MULTIPLIER = 1       # pega 1 task por vez (evita starvation)
CELERY_TASK_ACKS_LATE = True                # confirma task só após conclusão (sem perda)
CELERY_RESULT_EXPIRES = 3600               # resultados expiram em 1h

CELERY_BEAT_SCHEDULE = {
    'fetch-docker-logs': {
        'task': 'informatica.tasks.fetch_docker_logs_task',
        'schedule': 30.0,
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'GsdAutomatico.middleware.RequestLogMiddleware',
]

# Permite o uso de iframes dentro do próprio sistema (necessário para o painel de comunicações)
X_FRAME_OPTIONS = 'SAMEORIGIN'

# settings.py

CSRF_TRUSTED_ORIGINS = [
    'http://10.52.17.168:8080',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
]

ROOT_URLCONF = 'GsdAutomatico.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Ouvidoria.context_processors.ouvidoria_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'GsdAutomatico.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/Static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'Static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Evita erro 500 se um ficheiro específico faltar no manifest do collectstatic
WHITENOISE_MANIFEST_STRICT = False

# Arquivos com hash no nome são imutáveis — cache por 1 ano
WHITENOISE_MAX_AGE = 31536000

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR.parent, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Segurança ─────────────────────────────────────────────────────────────────
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_HTTPONLY = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# django-ratelimit
RATELIMIT_EXCEPTION_HANDLER = 'django_ratelimit.exceptions.Ratelimited'

LOGIN_URL = 'login:login'
LOGIN_REDIRECT_URL = 'Ouvidoria:index'
LOGOUT_REDIRECT_URL = 'login:login'

LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)
_log_file_writable = os.access(os.path.join(LOG_DIR, 'sistema.log'), os.W_OK) or \
                     not os.path.exists(os.path.join(LOG_DIR, 'sistema.log'))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}] {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        **({
            'file': {
                'level': 'INFO',
                'class': 'logging.handlers.TimedRotatingFileHandler',
                'filename': os.path.join(LOG_DIR, 'sistema.log'),
                'when': 'midnight',
                'backupCount': 7,
                'formatter': 'verbose',
                'encoding': 'utf-8',
            },
        } if _log_file_writable else {}),
    },
    'root': {
        'handlers': ['console', 'file'] if _log_file_writable else ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if _log_file_writable else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'file'] if _log_file_writable else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'] if _log_file_writable else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Upload size limits — tutorials can contain executables and other large files
DATA_UPLOAD_MAX_MEMORY_SIZE = 5368709120  # 5 GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5368709120  # 5 GB
