# Generated by Django 4.2.24 on 2025-12-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Efetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.CharField(blank=True, max_length=50, verbose_name='Posto')),
                ('quad', models.CharField(blank=True, max_length=50, verbose_name='QUAD')),
                ('especializacao', models.CharField(blank=True, max_length=100, verbose_name='Especialização')),
                ('saram', models.IntegerField(blank=True, null=True, unique=True, verbose_name='SARAM')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('nome_guerra', models.CharField(max_length=100, verbose_name='Nome de Guerra')),
                ('turma', models.CharField(blank=True, max_length=100, verbose_name='Turma')),
                ('situacao', models.CharField(blank=True, max_length=50, verbose_name='Situação')),
                ('om', models.CharField(blank=True, max_length=100, verbose_name='OM')),
                ('setor', models.CharField(blank=True, max_length=100, verbose_name='Setor')),
                ('subsetor', models.CharField(blank=True, max_length=100, verbose_name='Subsetor')),
                ('oficial', models.BooleanField(default=False, verbose_name='É Oficial?')),
                ('assinatura', models.TextField(blank=True, null=True, verbose_name='Assinatura Padrão (Base64)')),
                ('senha_unica', models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha Única')),
            ],
            options={
                'db_table': 'Efetivo',
            },
        ),
    ]
