# Generated by Django 4.2.24 on 2025-12-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efetivo',
            name='nome_guerra',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome de Guerra'),
        ),
    ]
