# Generated by Django 4.2.24 on 2025-12-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0003_alter_efetivo_nome_guerra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efetivo',
            name='nome_guerra',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome de Guerra'),
        ),
    ]
