# Generated by Django 4.2.24 on 2026-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0006_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações / Motivo da Baixa'),
        ),
    ]
