# Generated by Django 4.2.24 on 2026-03-17 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0007_efetivo_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoTrocaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_atual', models.CharField(blank=True, max_length=100, verbose_name='Setor Atual')),
                ('setor_destino', models.CharField(max_length=100, verbose_name='Setor Destino')),
                ('status', models.CharField(choices=[('pendente_atual', 'Aguardando Chefe Atual'), ('pendente_destino', 'Aguardando Chefe Destino'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente_atual', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('chefe_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacoes_saida', to='Secao_pessoal.efetivo', verbose_name='Chefe Atual')),
                ('chefe_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacoes_entrada', to='Secao_pessoal.efetivo', verbose_name='Chefe Destino')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_troca', to='Secao_pessoal.efetivo', verbose_name='Militar')),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
