# Generated by Django 4.2.24 on 2026-03-17 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0008_solicitacaotrocasetor'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='chefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores_chefiados', to='Secao_pessoal.efetivo', verbose_name='Chefe do Setor'),
        ),
    ]
