# Generated by Django 4.2.24 on 2026-03-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0009_setor_chefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='inspsau_finalidade',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Finalidade INSPSAU'),
        ),
    ]
