# Generated by Django 4.2.24 on 2026-03-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0010_efetivo_inspsau_finalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='documento_inspsau',
            field=models.FileField(blank=True, null=True, upload_to='inspsau_documentos/', verbose_name='Documento da INSPSAU'),
        ),
    ]
