# Generated by Django 4.2.24 on 2026-03-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0011_efetivo_documento_inspsau'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='inspsau_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da INSPSAU'),
        ),
    ]
