# Generated by Django 4.2.24 on 2026-04-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0012_efetivo_inspsau_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='dias_ferias_gozados',
            field=models.IntegerField(default=0, verbose_name='Dias de Férias Gozados'),
        ),
    ]
