# Generated by Django 4.2.24 on 2026-04-11 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0013_efetivo_dias_ferias_gozados'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoInspsau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('finalidade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Finalidade')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('documento', models.FileField(blank=True, null=True, upload_to='inspsau_historico/', verbose_name='Documento')),
                ('parecer', models.TextField(blank=True, null=True, verbose_name='Parecer')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_inspsau', to='Secao_pessoal.efetivo', verbose_name='Militar')),
            ],
            options={
                'verbose_name': 'Histórico de INSPSAU',
                'verbose_name_plural': 'Históricos de INSPSAU',
                'ordering': ['-data_registro'],
            },
        ),
    ]
