# Generated by Django 4.2.24 on 2026-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0014_historicoinspsau'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='inspsau_parecer',
            field=models.TextField(blank=True, null=True, verbose_name='Parecer da INSPSAU'),
        ),
    ]
