# Generated by Django 4.2.24 on 2026-04-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0015_efetivo_inspsau_parecer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efetivo',
            name='dias_ferias_gozados',
        ),
    ]
