# Generated by Django 4.2.24 on 2026-04-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0016_remove_efetivo_dias_ferias_gozados'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='arquivada',
            field=models.BooleanField(default=False, verbose_name='Arquivada'),
        ),
    ]
