# Generated by Django 4.2.24 on 2026-04-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0017_notificacao_arquivada'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
    ]
