# Generated by Django 4.2.24 on 2026-04-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0018_efetivo_deleted_efetivo_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Excluído (Lixeira)'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
    ]
