# Generated by Django 4.2.24 on 2026-04-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0019_notificacao_deleted_notificacao_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='notificacoes_anexos/', verbose_name='Anexo'),
        ),
    ]
