# Generated by Django 4.2.24 on 2026-04-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0021_remove_notificacao_to_caixa_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da Chamada')),
                ('presente', models.BooleanField(default=False, verbose_name='Presente')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='Secao_pessoal.efetivo', verbose_name='Militar')),
            ],
            options={
                'verbose_name': 'Registro de Chamada',
                'verbose_name_plural': 'Registros de Chamada',
                'ordering': ['-data', 'militar__nome_guerra'],
            },
        ),
    ]
