# Generated by Django 4.2.24 on 2026-05-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0022_registrochamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='boletim_prestacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Boletim de Prestação de Serviço'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='data_boletim_prestacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Boletim'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='data_inicio_prestacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início da Apresentação'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='data_portaria_prestacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Portaria'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='data_vencimento_prestacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento da Prestação'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='portaria_prestacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Portaria da Prestação de Serviço'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='unidade_prestacao_servico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade de Prestação de Serviço'),
        ),
    ]
