# Generated by Django 4.2.24 on 2026-06-06 16:17
# Rewritten to use CREATE INDEX CONCURRENTLY to avoid table locks in production.

from django.db import migrations, models


class Migration(migrations.Migration):
    # CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('Secao_pessoal', '0023_efetivo_boletim_prestacao_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='efetivo',
                    name='deleted',
                    field=models.BooleanField(db_index=True, default=False, verbose_name='Excluído'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "Efetivo_deleted_3de499b0" ON "Efetivo" ("deleted")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "Efetivo_deleted_3de499b0"',
                ),
            ],
        ),
    ]
