# Generated by Django 6.0.6 on 2026-06-18 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0024_alter_efetivo_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='ano_praca',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano de Praça'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='conjuge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cônjuge'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='contato_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Contato 1'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='contato_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Contato 2'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='contato_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Contato 3'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='contato_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Contato 4'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='data_desligamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Desligamento'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='documento_desligamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento de Publicação'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='email_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail 1'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail 2'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='email_3',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail 3'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='funcao_desligamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função (conforme publicado)'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='identidade_aer',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Identidade Aeronáutica'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='identidade_civil',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Identidade Civil'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='motivo_desligamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Desligamento'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.CreateModel(
            name='LotacaoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.CharField(blank=True, max_length=50, verbose_name='Posto/Grad')),
                ('quad', models.CharField(blank=True, max_length=50, verbose_name='Quadro')),
                ('especializacao', models.CharField(blank=True, max_length=100, verbose_name='Especialidade')),
                ('om', models.CharField(blank=True, max_length=100, verbose_name='OM')),
                ('vagas_previstas', models.PositiveIntegerField(default=0, verbose_name='TLP (Vagas Previstas)')),
            ],
            options={
                'verbose_name': 'Lotação de Pessoal (TLP)',
                'verbose_name_plural': 'Lotações de Pessoal (TLP)',
                'ordering': ['posto', 'quad', 'especializacao'],
                'constraints': [models.UniqueConstraint(fields=('posto', 'quad', 'especializacao', 'om'), name='uniq_lotacao_combo')],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEfetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(verbose_name='Data da Movimentação')),
                ('om_destino', models.CharField(blank=True, max_length=100, verbose_name='OM de Destino')),
                ('sigad_movimentacao', models.CharField(blank=True, max_length=100, verbose_name='SIGAD')),
                ('boletim_movimentacao', models.CharField(blank=True, max_length=100, verbose_name='Boletim (BCA/Bol. INT)')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='Secao_pessoal.efetivo', verbose_name='Militar')),
            ],
            options={
                'verbose_name': 'Movimentação de Efetivo',
                'verbose_name_plural': 'Movimentações de Efetivo',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
