# Generated by Django 6.0.6 on 2026-06-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0025_efetivo_ano_praca_efetivo_bairro_efetivo_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='sigad_prestacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SIGAD da Prestação de Serviço'),
        ),
    ]
