# Generated by Django 6.0.6 on 2026-06-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0026_add_sigad_prestacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='tlp',
            field=models.CharField(blank=True, max_length=3, verbose_name='TLP?'),
        ),
        migrations.AlterField(
            model_name='efetivo',
            name='om',
            field=models.CharField(blank=True, default='BINFAE-GL', max_length=100, verbose_name='OM'),
        ),
    ]
