# Generated by Django 4.2.24 on 2026-05-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Secao_pessoal', '0022_registrochamada'),
        ('Secao_operacoes', '0013_diretrizes_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaMissaoESI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('militares', models.ManyToManyField(blank=True, related_name='escalas_esi', to='Secao_pessoal.efetivo', verbose_name='Militares Escalados')),
                ('missao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escala_esi', to='Secao_operacoes.missao', verbose_name='Missão')),
            ],
            options={
                'verbose_name': 'Escala ESI',
                'verbose_name_plural': 'Escalas ESI',
                'ordering': ['-missao__data_missao'],
            },
        ),
    ]
