# Generated by Django 4.2.24 on 2026-05-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalamissaoesi',
            name='identificacao_pelotao',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Identificação do Pelotão/Seção (ex: 3º/5º ESI)'),
        ),
    ]
