# Generated by Django 4.2.24 on 2026-05-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='notificacoe_usuario_a5894e_idx',
            old_name='notificacoe_usuario_lida_idx',
        ),
    ]
