# Generated by Django 4.2.24 on 2026-04-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Secao_pessoal', '0015_efetivo_inspsau_parecer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Escala')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('militares', models.ManyToManyField(blank=True, related_name='escalas_vinculadas', to='Secao_pessoal.efetivo', verbose_name='Militares Vinculados')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Serviço')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='Secao_operacoes.escala')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_escalados', to='Secao_pessoal.efetivo')),
            ],
            options={
                'verbose_name': 'Turno de Escala',
                'verbose_name_plural': 'Turnos de Escala',
                'ordering': ['data'],
            },
        ),
    ]
