# Generated by Django 4.2.24 on 2026-04-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala',
            options={'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
        migrations.AddField(
            model_name='escala',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.CreateModel(
            name='PostoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Posto')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postos', to='Secao_operacoes.escala', verbose_name='Escala')),
            ],
            options={
                'verbose_name': 'Posto de Escala',
                'verbose_name_plural': 'Postos de Escala',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='turnoescala',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='Secao_operacoes.postoescala', verbose_name='Posto'),
        ),
    ]
