# Generated by Django 4.2.24 on 2026-04-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0002_alter_escala_options_escala_ativo_postoescala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='duracao_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Apenas para tipo Permanência', null=True, verbose_name='Duração (horas)'),
        ),
        migrations.AddField(
            model_name='escala',
            name='tipo',
            field=models.CharField(choices=[('24h', '24 Horas'), ('turno', 'Turno (6h)'), ('permanencia', 'Permanência'), ('sbv', 'SBV — Sobre Aviso')], default='24h', max_length=20, verbose_name='Tipo de Serviço'),
        ),
        migrations.AddField(
            model_name='postoescala',
            name='horario',
            field=models.CharField(blank=True, help_text='Ex: 0h às 6h, 6h às 12h, Manhã, Tarde...', max_length=50, verbose_name='Horário'),
        ),
    ]
