# Generated by Django 4.2.24 on 2026-05-05 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Secao_pessoal', '0022_registrochamada'),
        ('Secao_operacoes', '0003_escala_duracao_horas_escala_tipo_postoescala_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da OMIS')),
                ('nome_missao', models.CharField(max_length=200, verbose_name='Nome/Tipo da Missão')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('objetivo', models.TextField(verbose_name='Objetivo da Missão')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('acionador', models.CharField(blank=True, max_length=200, verbose_name='Acionador (Ofício Nº)')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_missao', models.DateField(verbose_name='Data da Missão')),
                ('horario_chamada', models.TimeField(blank=True, null=True, verbose_name='Chamada')),
                ('horario_armamento', models.TimeField(blank=True, null=True, verbose_name='Armamento')),
                ('horario_alimentacao', models.TimeField(blank=True, null=True, verbose_name='Alimentação')),
                ('horario_sala_sgt', models.TimeField(blank=True, null=True, verbose_name='Horário Sala Sgt de Dia')),
                ('horario_saida', models.TimeField(blank=True, null=True, verbose_name='Saída do GSD GL')),
                ('horario_pronto', models.TimeField(blank=True, null=True, verbose_name='Pronto no Objetivo')),
                ('transporte', models.CharField(blank=True, max_length=200, verbose_name='Transporte')),
                ('radio_qtd', models.PositiveSmallIntegerField(default=0, verbose_name='Qtd. Rádios')),
                ('radio_canal', models.CharField(blank=True, max_length=50, verbose_name='Canal Rádio')),
                ('uniforme', models.CharField(blank=True, max_length=100, verbose_name='Uniforme')),
                ('observacoes_armamento', models.TextField(blank=True, verbose_name='Observações sobre Armamento (RIMB)')),
                ('efetivo_so_sgt', models.PositiveSmallIntegerField(default=0, verbose_name='SO/SGT')),
                ('efetivo_cb', models.PositiveSmallIntegerField(default=0, verbose_name='CB')),
                ('efetivo_s1', models.PositiveSmallIntegerField(default=0, verbose_name='S1')),
                ('efetivo_s2', models.PositiveSmallIntegerField(default=0, verbose_name='S2')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cmt_missao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missoes_como_cmt', to='Secao_pessoal.efetivo', verbose_name='Comandante da Missão')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ManyToManyField(blank=True, related_name='missoes_equipe', to='Secao_pessoal.efetivo', verbose_name='Equipe')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missoes_como_mot', to='Secao_pessoal.efetivo', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Missão (OMIS)',
                'verbose_name_plural': 'Missões (OMIS)',
                'ordering': ['-data_missao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=100, verbose_name='Equipamento')),
                ('quantidade', models.PositiveSmallIntegerField(default=0, verbose_name='Qtd')),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='Secao_operacoes.missao')),
            ],
            options={
                'verbose_name': 'Item de Equipamento',
                'verbose_name_plural': 'Itens de Equipamento',
            },
        ),
        migrations.CreateModel(
            name='ItemArmamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arma', models.CharField(max_length=100, verbose_name='Arma')),
                ('quantidade', models.PositiveSmallIntegerField(default=0, verbose_name='Qtd')),
                ('carregadores', models.PositiveSmallIntegerField(default=0, verbose_name='Carregadores')),
                ('cartuchos', models.PositiveSmallIntegerField(default=0, verbose_name='Cartuchos')),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armamentos', to='Secao_operacoes.missao')),
            ],
            options={
                'verbose_name': 'Item de Armamento',
                'verbose_name_plural': 'Itens de Armamento',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoOperacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefe_sop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chefe_sop_config', to='Secao_pessoal.efetivo', verbose_name='Chefe da Seção de Operações')),
                ('comandante_gsd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandante_gsd_config', to='Secao_pessoal.efetivo', verbose_name='Comandante do GSD GL')),
            ],
            options={
                'verbose_name': 'Configuração de Operações',
                'verbose_name_plural': 'Configurações de Operações',
            },
        ),
    ]
