# Generated by Django 4.2.24 on 2026-05-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0004_missao_itemequipamento_itemarmamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Equipamento')),
            ],
            options={
                'verbose_name': 'Equipamento (Catálogo)',
                'verbose_name_plural': 'Equipamentos (Catálogo)',
                'ordering': ['nome'],
            },
        ),
    ]
