# Generated by Django 4.2.24 on 2026-05-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0005_equipamentocatalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmamentoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da Arma')),
                ('carregadores_por_unidade', models.PositiveSmallIntegerField(default=0, verbose_name='Carregadores por arma')),
                ('cartuchos_por_unidade', models.PositiveSmallIntegerField(default=0, verbose_name='Cartuchos por arma')),
            ],
            options={
                'verbose_name': 'Armamento (Catálogo)',
                'verbose_name_plural': 'Armamentos (Catálogo)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RadioCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome/Modelo do Rádio')),
                ('canal_padrao', models.CharField(blank=True, max_length=50, verbose_name='Canal Padrão')),
            ],
            options={
                'verbose_name': 'Rádio (Catálogo)',
                'verbose_name_plural': 'Rádios (Catálogo)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UniformeCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Uniforme')),
            ],
            options={
                'verbose_name': 'Uniforme (Catálogo)',
                'verbose_name_plural': 'Uniformes (Catálogo)',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='missao',
            name='radio_nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome/Modelo do Rádio'),
        ),
    ]
