# Generated by Django 4.2.24 on 2026-05-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0006_armamentocatalogo_radiocatalogo_uniformecatalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='efetivo_of',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='OF'),
        ),
    ]
