# Generated by Django 4.2.24 on 2026-05-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0007_missao_efetivo_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='cmt_a_cargo',
            field=models.CharField(blank=True, max_length=200, verbose_name='CMT a cargo de'),
        ),
        migrations.AddField(
            model_name='missao',
            name='efetivo_rec',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='REC'),
        ),
        migrations.AddField(
            model_name='missao',
            name='equipe_a_cargo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Equipe a cargo de'),
        ),
        migrations.AddField(
            model_name='missao',
            name='mot_a_cargo',
            field=models.CharField(blank=True, max_length=200, verbose_name='MOT a cargo de'),
        ),
    ]
