# Generated by Django 4.2.24 on 2026-05-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0008_missao_cmt_a_cargo_missao_efetivo_rec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Descrição')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_extras', to='Secao_operacoes.missao')),
            ],
            options={
                'verbose_name': 'Horário Extra',
                'ordering': ['ordem'],
            },
        ),
    ]
