# Generated by Django 4.2.24 on 2026-05-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0009_itemhorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaooperacoes',
            name='diretriz_padrao_1',
            field=models.TextField(blank=True, default='Manter o Oficial de serviço do GSD GL / Sargento de Dia informado do início e do término da missão.', verbose_name='Diretriz padrão 1'),
        ),
        migrations.AddField(
            model_name='configuracaooperacoes',
            name='diretriz_padrao_2',
            field=models.TextField(blank=True, default='O relatório da missão deverá ser confeccionado pelo Cmt da mesma e entregue, em até 24h, ao Sgt de dia ao GSD GL. Deverá conter além das informações inerentes a missão, o horário do término da mesma, as alterações de cumprimento do quadro de horários, transporte, alimentação, faltas, sugestões, ocorrências, bem como as providências adotadas.', verbose_name='Diretriz padrão 2'),
        ),
        migrations.AddField(
            model_name='missao',
            name='diretriz_1',
            field=models.TextField(blank=True, verbose_name='Diretriz 1'),
        ),
        migrations.AddField(
            model_name='missao',
            name='diretriz_2',
            field=models.TextField(blank=True, verbose_name='Diretriz 2'),
        ),
    ]
