# Generated by Django 4.2.24 on 2026-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0012_configuracaooperacoes_observacoes_armamento_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaooperacoes',
            name='diretrizes_padrao_json',
            field=models.TextField(blank=True, default='', verbose_name='Diretrizes padrão (JSON)'),
        ),
        migrations.AddField(
            model_name='missao',
            name='diretrizes_json',
            field=models.TextField(blank=True, default='', verbose_name='Diretrizes (JSON)'),
        ),
    ]
