# Generated by Django 4.2.24 on 2026-05-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0013_diretrizes_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACargaOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name="Opção 'A Cargo de'")),
            ],
            options={
                'verbose_name': "Opção 'A Cargo de'",
                'verbose_name_plural': "Opções 'A Cargo de'",
                'ordering': ['nome'],
            },
        ),
    ]
