# Generated by Django 4.2.24 on 2026-05-12 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0022_registrochamada'),
        ('Secao_operacoes', '0014_acarga_opcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaooperacoes',
            name='comandante_esi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandante_esi_config', to='Secao_pessoal.efetivo', verbose_name='Comandante da ESI'),
        ),
    ]
