# Generated by Django 4.2.24 on 2026-05-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0015_configuracaooperacoes_comandante_esi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaooperacoes',
            name='chefe_sop',
        ),
        migrations.RemoveField(
            model_name='configuracaooperacoes',
            name='comandante_esi',
        ),
        migrations.RemoveField(
            model_name='configuracaooperacoes',
            name='comandante_gsd',
        ),
    ]
