# Generated by Django 4.2.24 on 2026-05-15 17:57

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0017_itemhorario_slot_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='missao',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.ExtractYear('data_emissao'), models.F('numero'), name='unique_omis_numero_por_ano'),
        ),
    ]
