# Generated by Django 4.2.24 on 2026-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_operacoes', '0019_missao_efetivo_grupos_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaooperacoes',
            name='diretriz_padrao_1',
            field=models.TextField(blank=True, default='Manter o Oficial de serviço do BINFAE GL / Sargento de Dia informado do início e do término da missão.', verbose_name='Diretriz padrão 1'),
        ),
        migrations.AlterField(
            model_name='configuracaooperacoes',
            name='diretriz_padrao_2',
            field=models.TextField(blank=True, default='O relatório da missão deverá ser confeccionado pelo Cmt da mesma e entregue, em até 24h, ao Sgt de dia ao BINFAE GL. Deverá conter além das informações inerentes a missão, o horário do término da mesma, as alterações de cumprimento do quadro de horários, transporte, alimentação, faltas, sugestões, ocorrências, bem como as providências adotadas.', verbose_name='Diretriz padrão 2'),
        ),
        migrations.AlterField(
            model_name='missao',
            name='horario_saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Saída do BINFAE GL'),
        ),
    ]
