# Generated by Django 4.2.24 on 2026-06-12 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Secao_pessoal', '0024_alter_efetivo_deleted'),
        ('Secao_operacoes', '0020_alter_configuracaooperacoes_diretriz_padrao_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoEspecialEfetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('licenca', 'Licença / Férias'), ('afastamento', 'Afastamento Médico'), ('tdo', 'TDO / Curso'), ('outro', 'Outro')], max_length=20, verbose_name='Situação')),
                ('data_inicio', models.DateField(verbose_name='Data início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data fim')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('efetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacoes_especiais', to='Secao_pessoal.efetivo', verbose_name='Militar')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Situação Especial',
                'verbose_name_plural': 'Situações Especiais',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
