# Generated by Django 4.2.24 on 2026-06-10 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Secao_pessoal', '0024_alter_efetivo_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Curso',
                'verbose_name_plural': 'Tipos de Curso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CursoEfetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateField(verbose_name='Data de Realização')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('instituicao', models.CharField(blank=True, max_length=200, verbose_name='Instituição/Local')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='scim/certificados/', verbose_name='Certificado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('efetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='Secao_pessoal.efetivo')),
                ('tipo_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SCIM.tipocurso', verbose_name='Tipo de Curso')),
            ],
            options={
                'verbose_name': 'Curso do Efetivo',
                'verbose_name_plural': 'Cursos do Efetivo',
                'ordering': ['-data_realizacao'],
            },
        ),
    ]
