# Generated by Django 4.2.24 on 2026-06-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCIM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoefetivo',
            name='data_validade',
        ),
    ]
