# Generated by Django 6.0.6 on 2026-06-25 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Usuário')),
                ('nome_guerra', models.CharField(blank=True, max_length=100, verbose_name='Nome de Guerra')),
                ('permissao', models.CharField(blank=True, max_length=100, verbose_name='Permissão')),
                ('secao', models.CharField(blank=True, max_length=30, verbose_name='Seção')),
                ('acao', models.CharField(blank=True, max_length=30, verbose_name='Ação')),
                ('objeto_tipo', models.CharField(blank=True, max_length=60, verbose_name='Tipo de Objeto')),
                ('objeto_id', models.CharField(blank=True, max_length=60, verbose_name='ID/Número do Objeto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['secao', 'criado_em'], name='auditoria_l_secao_50131d_idx'), models.Index(fields=['username'], name='auditoria_l_usernam_ca1acb_idx')],
            },
        ),
    ]
