# Generated by Django 4.2.24 on 2026-03-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Secao_pessoal', '0009_setor_chefe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cautela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('assinatura_sobreaviso', models.TextField()),
                ('assinatura_recebedor', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('recebedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautelas_recebidas', to='Secao_pessoal.efetivo')),
                ('sobreaviso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautelas_liberadas', to='Secao_pessoal.efetivo')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='SubgrupoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='informatica.grupomaterial')),
            ],
            options={
                'unique_together': {('grupo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Interno')),
                ('serial', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('funcionando', models.BooleanField(default=True, verbose_name='Em funcionamento?')),
                ('motivo_defeito', models.TextField(blank=True, null=True, verbose_name='Motivo do Defeito')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Cautela')),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='informatica.subgrupomaterial')),
            ],
        ),
        migrations.CreateModel(
            name='CautelaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cautela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='informatica.cautela')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informatica.material')),
            ],
        ),
    ]
