# Generated by Django 4.2.24 on 2026-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='atributos_extras',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Atributos Específicos'),
        ),
    ]
