# Generated by Django 4.2.24 on 2026-03-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0002_material_atributos_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='serial',
            field=models.CharField(max_length=100, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='material',
            name='subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='informatica.subgrupomaterial'),
        ),
    ]
