# Generated by Django 4.2.24 on 2026-03-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0003_alter_material_serial_alter_material_subgrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautela',
            name='nome_missao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Missão/Formatura'),
        ),
        migrations.AddField(
            model_name='cautela',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone de Contato'),
        ),
        migrations.AddField(
            model_name='cautelaitem',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cautelaitem',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
