# Generated by Django 4.2.24 on 2026-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0004_cautela_nome_missao_cautela_telefone_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautelaitem',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade Total'),
        ),
        migrations.AddField(
            model_name='material',
            name='quantidade_disponivel',
            field=models.IntegerField(default=1, verbose_name='Quantidade Disponível'),
        ),
        migrations.AlterField(
            model_name='material',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série'),
        ),
    ]
