# Generated by Django 4.2.24 on 2026-03-25 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0009_setor_chefe'),
        ('informatica', '0005_cautelaitem_quantidade_material_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautela',
            name='assinatura_devolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cautela',
            name='recebedor_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_gerais', to='Secao_pessoal.efetivo'),
        ),
        migrations.AddField(
            model_name='cautelaitem',
            name='assinatura_devolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cautelaitem',
            name='recebedor_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_individuais', to='Secao_pessoal.efetivo'),
        ),
    ]
