# Generated by Django 4.2.24 on 2026-03-31 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0006_cautela_assinatura_devolucao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome/Número do Armário')),
                ('localizacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Localização (Sala/Setor)')),
            ],
        ),
        migrations.CreateModel(
            name='Prateleira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome/Número da Prateleira')),
                ('armario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prateleiras', to='informatica.armario')),
            ],
            options={
                'unique_together': {('armario', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='prateleira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='informatica.prateleira', verbose_name='Localização na Prateleira'),
        ),
    ]
