# Generated by Django 4.2.24 on 2026-04-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0012_efetivo_inspsau_validade'),
        ('informatica', '0007_armario_prateleira_material_prateleira'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='secao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_informatica', to='Secao_pessoal.setor', verbose_name='Seção/Setor alocado'),
        ),
    ]
