# Generated by Django 4.2.24 on 2026-04-14 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('informatica', '0008_material_secao'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(choices=[('geral', 'Geral'), ('ouvidoria', 'Ouvidoria'), ('operacoes', 'Seção de Operações'), ('pessoal', 'Seção de Pessoal'), ('informatica', 'Informática'), ('outros', 'Outros')], default='geral', max_length=30, verbose_name='Seção')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secao_profile', to='auth.group')),
            ],
            options={
                'verbose_name': 'Perfil do Grupo',
                'verbose_name_plural': 'Perfis dos Grupos',
            },
        ),
    ]
