# Generated by Django 4.2.24 on 2026-05-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0009_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='localizacao_texto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização / Seção (texto)'),
        ),
    ]
