# Generated by Django 4.2.24 on 2026-05-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0022_registrochamada'),
        ('informatica', '0010_material_localizacao_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoComandantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefe_sop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Secao_pessoal.efetivo', verbose_name='Chefe da Seção de Operações')),
                ('comandante_bagl', models.ForeignKey(blank=True, limit_choices_to={'oficial': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Secao_pessoal.efetivo', verbose_name='Comandante da Base (BAGL)')),
                ('comandante_esi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Secao_pessoal.efetivo', verbose_name='Comandante do Esquadrão de Segurança das Instalações')),
                ('comandante_gsd', models.ForeignKey(blank=True, limit_choices_to={'oficial': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Secao_pessoal.efetivo', verbose_name='Comandante do GSD')),
            ],
            options={
                'verbose_name': 'Configuração de Comandantes',
                'verbose_name_plural': 'Configurações de Comandantes',
            },
        ),
    ]
