# Generated by Django 4.2.24 on 2026-06-06 16:17
# Rewritten to use CREATE INDEX CONCURRENTLY to avoid table locks in production.

from django.db import migrations, models


class Migration(migrations.Migration):
    # CONCURRENTLY cannot run inside a transaction.
    atomic = False

    dependencies = [
        ('informatica', '0011_configuracaocomandantes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='cautela',
                    name='ativa',
                    field=models.BooleanField(db_index=True, default=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "informatica_cautela_ativa_98f23994" ON "informatica_cautela" ("ativa")',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "informatica_cautela_ativa_98f23994"',
                ),
            ],
        ),
    ]
