# Generated by Django 6.0.6 on 2026-06-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0012_alter_cautela_ativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Envio remoto ativo')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Host/IP do servidor reserva')),
                ('porta', models.PositiveIntegerField(default=22, verbose_name='Porta SSH')),
                ('usuario', models.CharField(blank=True, max_length=150, verbose_name='Usuário SSH')),
                ('senha_criptografada', models.TextField(blank=True, verbose_name='Senha (armazenada criptografada)')),
                ('diretorio_destino', models.CharField(blank=True, default='/backups/gsd-automatico', max_length=500, verbose_name='Diretório de destino no servidor reserva')),
                ('horario_execucao', models.TimeField(default='03:00', verbose_name='Horário diário de execução do backup')),
                ('dias_retencao_local', models.PositiveIntegerField(default=30, verbose_name='Dias de retenção dos backups locais')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Backup Remoto',
                'verbose_name_plural': 'Configuração de Backup Remoto',
            },
        ),
        migrations.CreateModel(
            name='BackupExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('sucesso_local', 'Sucesso (apenas local)'), ('sucesso_remoto', 'Sucesso (local + enviado ao servidor reserva)'), ('erro', 'Erro')], default='em_andamento', max_length=20)),
                ('arquivo_db', models.CharField(blank=True, max_length=500, verbose_name='Arquivo local do dump do banco')),
                ('arquivo_media', models.CharField(blank=True, max_length=500, verbose_name='Arquivo local do tar de mídia')),
                ('tamanho_db_bytes', models.BigIntegerField(default=0)),
                ('tamanho_media_bytes', models.BigIntegerField(default=0)),
                ('enviado_remoto', models.BooleanField(default=False)),
                ('erro_detalhe', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Execução de Backup',
                'verbose_name_plural': 'Execuções de Backup',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
