# Generated by Django 6.0.6 on 2026-06-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0013_backupdestino_backupexecucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdestino',
            name='host_key_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='Impressão digital da chave SSH (fixada na primeira conexão)'),
        ),
    ]
