# Generated by Django 6.0.6 on 2026-06-28 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao_pessoal', '0025_efetivo_ano_praca_efetivo_bairro_efetivo_cep_and_more'),
        ('informatica', '0014_backupdestino_host_key_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautela',
            name='recebedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautelas_recebidas', to='Secao_pessoal.efetivo'),
        ),
        migrations.AlterField(
            model_name='cautela',
            name='recebedor_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_gerais', to='Secao_pessoal.efetivo'),
        ),
        migrations.AlterField(
            model_name='cautela',
            name='sobreaviso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautelas_liberadas', to='Secao_pessoal.efetivo'),
        ),
        migrations.AlterField(
            model_name='cautelaitem',
            name='recebedor_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_individuais', to='Secao_pessoal.efetivo'),
        ),
    ]
