# Generated by Django 4.2.24 on 2026-05-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrochamada',
            name='presente',
        ),
        migrations.AddField(
            model_name='registrochamada',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Presente'), ('F', 'Falta'), ('M', 'Missão'), ('ESV', 'Entrando de Serviço'), ('SSV', 'Saindo de Serviço'), ('DPC', 'Dispensado pelo Chefe')], max_length=5, null=True, verbose_name='Status'),
        ),
    ]
